import type { Metadata } from "next";
import { Source_Serif_4 } from "next/font/google";
import "@/app/globals.css";
import { getServerSession } from "next-auth"
import SessionProvider from "@/components/providers/SessionProvider";
import Navbar from "@/components/layout/navbar";

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-source-serif",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${sourceSerif.variable} antialiased`}>
        <div id="portal-root" />
        <SessionProvider session={session}>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
